### ISSUE TITLE
Documentacao do projeto

### ISSUE THREAD

**Issue by luan03** [andregparada/food_explorer_frontend#1]
Fala Andre, beleza?

Cara, o Igor me disse que voce precisa de ajuda, entao vamos la:

Crie um README.md contendo as seguintes informacoes do seu projeto frontend:

- Stack utilizada
- Estrutura de pastas e arquivos
- Como rodar

A partir disso eu posso ir te ajudando a melhorar seu projeto.

Por fim, fechar essa issue após fazer os itens solicitados.

:)

**Comment by andregparada** [comment]
Oi, Luan. Muito obrigado pela sua ajuda! Criei a pasta, mas é a primeira vez que faço esse tipo de descritivo, como estou começando no meio agora. Se puder, veja se está tudo certo. Se não há nada faltando ou algo redundante.

Muito obrigado pela sua ajuda
